name: Actualizar precios Cardmarket

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Descargar Price Guide
        run: |
          curl -L \
            -o price_guide.json \
            "https://downloads.s3.cardmarket.com/productCatalog/priceGuide/price_guide_6.json"

      - name: Descargar catálogo de cartas
        run: |
          curl -L \
            -o products_singles.json \
            "https://downloads.s3.cardmarket.com/productCatalog/productList/products_singles_6.json"

      - name: Comprobar archivos
        run: |
          echo "Price Guide:"
          wc -c price_guide.json

          echo "Catálogo:"
          wc -c products_singles.json

      - name: Procesar datos de Cardmarket
        run: |
          python scripts/procesar_cardmarket.py

      - name: Guardar cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add price_guide.json products_singles.json pokemon_cards.json pitch_black.json

          git diff --cached --quiet || git commit -m "Actualizar datos Cardmarket"

          git push
